# version: "3.8"
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3    # More partitions = More parallelism
      KAFKA_LOG_RETENTION_HOURS: 1  # Clear old messages faster
      KAFKA_COMPRESSION_TYPE: snappy # Faster transport
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_KAFKA_BROKERCONNECT: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092 
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    depends_on:
      - kafka
      - zookeeper
    entrypoint: /bin/sh -c "until nc -z kafka 9092; do echo 'Waiting for Kafka...'; sleep 5; done; until nc -z zookeeper 2181; do echo 'Waiting for Zookeeper...'; sleep 5; done; /etc/confluent/docker/run"
